### ISSUE TITLE
Opera: Failed to load Manifest

### ISSUE THREAD

**Issue by peterpme** [bradjasper/focus-extension#1]
![image](https://user-images.githubusercontent.com/1211905/29585184-d598457c-874b-11e7-97d9-15947c3db803.png)

Hey, awesome plugin! Opera is built on Chrome and can use the same extensions. Unfortunately, I seem to be getting this issue. 

Any help would be appreciated.

Thanks!

**Comment by bradjasper** [comment]
Hello, I believe with Opera you have to unzip the file, then load the extension in developer mode. You can select any file in the folder to load.

I'm trying to get an official Opera plugin approved, but it's been pending in the queue for a few weeks.

Please let me know if this works for you!
