### ISSUE TITLE
Focus not working in Edge

### ISSUE THREAD

**Issue by arturogh** [bradjasper/focus-extension#11]
Hi,

I have Edge for MacOS Version 80.0.361.5 running, have installed Focus extension 2.5 and pages are not being blocked.

**Comment by harbortype** [comment]
Same here. I’ve found version 2.4 of the extension mostly works, but it does not block Twitter.

**Comment by natefromfargo** [comment]
Ditto, not seeing any functionality in Edge (81.0.416.58). I believe it has something to do with security permission registration. 
![Screen Shot 2020-04-30 at 9 06 03 AM](https://user-images.githubusercontent.com/15983913/80719954-d4b25680-8ac1-11ea-9475-5d0503ab8ace.png)

**Comment by arryanggaputra** [comment]
@natefromfargo @bradjasper @harbortype There's an error in this browser extension, that's why this extension doesn't work in Microsoft Edge. You can change the `focus.js` in this extension with this script to make this extension works in Edge browser.

```javascript
var vendor = getBrowserType();

var conn = new FocusConnection();
conn.version = config.version;
conn.platform = BrowserDetect.browser;

var isWhitelist = false;
var isFocusing = false;
var enableCloseBrowserTabs = false;
var redirectURL;
var regexSites = [];
var compiledRegexSites = [];

function reset() {
  isWhitelist = false;
  isFocusing = false;
  regexSites = [];
  compiledRegexSites = [];
}

conn.focus = function (data) {
  regexSites = [];
  compiledRegexSites = [];

  if (!data.regexSites || data.regexSites.length == 0) {
    return;
  }

  console.log("Focusing");

  isWhitelist = data.whitelist;
  regexSites = data.regexSites;
  compiledRegexSites = compileRegexSites(data.regexSites);
  isFocusing = true;
  enableCloseBrowserTabs = data.enableCloseBrowserTabs;
  redirectURL = data.redirectURL;

  var filters = { urls: ["<all_urls>"], types: ["main_frame", "sub_frame"] };
  var extraInfoSpec = ["blocking"];

  reloadShouldBeBlockedPages(compiledRegexSites);

  processTabs();
};

conn.unfocus = function () {
  console.log("Unfocusing");
  reset();
  reloadBlockedPages();
};

conn.cleanup = function () {
  console.log("Cleaning up request handler");
  reset();
};

conn.connect();

function handleBeforeNavigate(navDetails) {
  if (!isFocusing) {
    return;
  }
  //console.log("handleBeforeNavigate");

  if (navDetails.frameId == 0) {
    checkTabURL(navDetails.tabId, navDetails.url);
  }
}

function processTabs() {
  //console.log("processTabs");

  console.log("browser", vendor);

  vendor.tabs.query({}, function (tabs) {
    if (vendor.runtime.lastError) {
      console.log("error fetching tabs", error);
      return;
    }

    for (let tab of tabs) {
      checkTabURL(tab.id, tab.url);
    }
  });
}

function checkTabURL(tabId, url) {
  if (url.indexOf("about:") == 0) {
    return false;
  }

  if (urlIsBlocked(url, compiledRegexSites, isWhitelist)) {
    if (enableCloseBrowserTabs) {
      chrome.tabs.remove(tabId);
    } else {
      var newURL = redirectURL + "?focus_url=" + encodeURIComponent(url);
      chrome.tabs.update(tabId, { url: newURL });
    }
    return true;
  }
}

vendor.webNavigation.onBeforeNavigate.addListener(handleBeforeNavigate);

```
![image](https://user-images.githubusercontent.com/4743772/90839751-710aac80-e382-11ea-91b5-55bb57389ded.png)

**Comment by natefromfargo** [comment]
> @natefromfargo @bradjasper @harbortype There's an error in this browser extension, that's why this extension doesn't work in Microsoft Edge. You can change the `focus.js` in this extension with this script to make this extension works in Edge browser.
> 
> ```js
> var vendor = getBrowserType();
> 
> var conn = new FocusConnection();
> conn.version = config.version;
> conn.platform = BrowserDetect.browser;
> 
> var isWhitelist = false;
> var isFocusing = false;
> var enableCloseBrowserTabs = false;
> var redirectURL;
> var regexSites = [];
> var compiledRegexSites = [];
> 
> function reset() {
>   isWhitelist = false;
>   isFocusing = false;
>   regexSites = [];
>   compiledRegexSites = [];
> }
> 
> conn.focus = function (data) {
>   regexSites = [];
>   compiledRegexSites = [];
> 
>   if (!data.regexSites || data.regexSites.length == 0) {
>     return;
>   }
> 
>   console.log("Focusing");
> 
>   isWhitelist = data.whitelist;
>   regexSites = data.regexSites;
>   compiledRegexSites = compileRegexSites(data.regexSites);
>   isFocusing = true;
>   enableCloseBrowserTabs = data.enableCloseBrowserTabs;
>   redirectURL = data.redirectURL;
> 
>   var filters = { urls: ["<all_urls>"], types: ["main_frame", "sub_frame"] };
>   var extraInfoSpec = ["blocking"];
> 
>   reloadShouldBeBlockedPages(compiledRegexSites);
> 
>   processTabs();
> };
> 
> conn.unfocus = function () {
>   console.log("Unfocusing");
>   reset();
>   reloadBlockedPages();
> };
> 
> conn.cleanup = function () {
>   console.log("Cleaning up request handler");
>   reset();
> };
> 
> conn.connect();
> 
> function handleBeforeNavigate(navDetails) {
>   if (!isFocusing) {
>     return;
>   }
>   //console.log("handleBeforeNavigate");
> 
>   if (navDetails.frameId == 0) {
>     checkTabURL(navDetails.tabId, navDetails.url);
>   }
> }
> 
> function processTabs() {
>   //console.log("processTabs");
> 
>   console.log("browser", vendor);
> 
>   vendor.tabs.query({}, function (tabs) {
>     if (vendor.runtime.lastError) {
>       console.log("error fetching tabs", error);
>       return;
>     }
> 
>     for (let tab of tabs) {
>       checkTabURL(tab.id, tab.url);
>     }
>   });
> }
> 
> function checkTabURL(tabId, url) {
>   if (url.indexOf("about:") == 0) {
>     return false;
>   }
> 
>   if (urlIsBlocked(url, compiledRegexSites, isWhitelist)) {
>     if (enableCloseBrowserTabs) {
>       chrome.tabs.remove(tabId);
>     } else {
>       var newURL = redirectURL + "?focus_url=" + encodeURIComponent(url);
>       chrome.tabs.update(tabId, { url: newURL });
>     }
>     return true;
>   }
> }
> 
> vendor.webNavigation.onBeforeNavigate.addListener(handleBeforeNavigate);
> ```
> 
> ![image](https://user-images.githubusercontent.com/4743772/90839751-710aac80-e382-11ea-91b5-55bb57389ded.png)

Thanks @arryanggaputra ! That worked perfectly. @bradjasper you owe this guy a coffee ☕ - been waiting on a fix for 5 months and even submitted a support ticket.

**Comment by JoaoTMDias** [comment]
Thanks @arryanggaputra for your solution!
I've opened a pull request, let's see if @bradjasper see this.

The link for the PR:
https://github.com/bradjasper/focus-extension/pull/12

**Comment by elankiderman** [comment]
just noting that @arryanggaputra 's suggestion also fixed the extension in a Chromium browser called Arc

**Comment by Kullenej** [comment]
> just noting that @arryanggaputra 's suggestion also fixed the extension in a Chromium browser called Arc

How did you do that? I can't even get Arc to accept the .xpi. And where do you place the script??

**Comment by bradjasper** [comment]
I'm merging Edge/Arc support in Focus extension (will be published soon), and have added native Arc support in the next major version of Focus, send an email to support@heyfocus.com for testing.

**Comment by bradjasper** [comment]
This has been released as https://github.com/bradjasper/focus-extension/releases/tag/v2.6.0 — this should fix support for Microsoft Edge and Arc.

**Comment by Kullenej** [comment]
Does this update also come with the SetApp-version?

**Comment by bradjasper** [comment]
Yep this will work with the Setapp version as well, let me know if you hit any issues!
