### ISSUE TITLE
Block the access to the extentions while in focus  

### ISSUE THREAD

**Issue by bluecapone** [bradjasper/focus-extension#13]
It would be nice to block access to the addons/extensions menu while I am in focus mode.
We this feature prevents the user to remove the extension.

Best Regards,
And you have done a nice job with the extension

**Comment by Mylowpolygon** [comment]
that would be great!

**Comment by bradjasper** [comment]
Hello, I've got this working in Focus 2.0.6, it will be out ASAP!

**Comment by half-adder** [comment]
Is there a documentation page for how to achieve this? I can't find it

**Comment by bradjasper** [comment]
If you update to the latest extension and add the block page

about:addons

It should work as expected, I'll get this documented somewhere!

**Comment by half-adder** [comment]
Gotcha - thanks so much!
