### ISSUE TITLE
Plans for Arc Browser

### ISSUE THREAD

**Issue by jvanbaarsen** [bradjasper/focus-extension#15]
Hi there,

Are there plans to make this work in [Arc Browser](https://arc.net/)? I tried loading this extension but then get this error:

![CleanShot 2023-02-06 at 13 15 41](https://user-images.githubusercontent.com/1362793/216968888-e95dd976-4b99-4363-8442-13db153f5786.png)

**Comment by bradjasper** [comment]
Hello, I am working on native support for Arc—I have it working in the next major version of Focus that will be in alpha testing soon, and am will backport it to older versions of Focus after that.

The next version supports multiple profiles and is a complete rewrite—I'm looking for testers so if you want to try Arc + Profiles please email support@heyfocus.com

**Comment by bradjasper** [comment]
In the meantime does it seem like this pull request might solve the issue? Using vendor instead of browser? https://github.com/bradjasper/focus-extension/pull/12/files

**Comment by jvanbaarsen** [comment]
@bradjasper I'm sending you an e-mail for testing it out! 

The PR you linked is working indeed!
