### ISSUE TITLE
Extension manifest version

### ISSUE THREAD

**Issue by rakuzen25** [bradjasper/focus-extension#16]
Hi! Arc user here. Just loaded the unpacked extension via dev mode, everything works smoothly except a warning for the extension:

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

Any plans to update the manifest version? I have no experience with extension development, so I'm not sure how much work this is going to take :p

**Comment by bradjasper** [comment]
Hello sorry for the delay, Focus now has native support for Arc so this shouldn't be an issue anymore!
