### ISSUE TITLE
Extension no longer works for Arc Browser

### ISSUE THREAD

**Issue by badeendjuh** [bradjasper/focus-extension#17]
For a short while the browser extension worked for the Arc Browser, but somewhere around version ~0.97 the extension disappeared. When trying to drag to .xpi file into the extension page to have it installed, there's a small glitch to show it tried something, but there is no error or other feedback. The extension is not installed.

Current Arc Browser version:
Version 0.101.2 (38549)
Chromium Engine Version 112.0.5615.137

**Comment by bradjasper** [comment]
Thanks for letting me know, I am investigating and also working on native Arc support. Will have an update soon!

**Comment by bradjasper** [comment]
Hello, we just added native Arc support to Focus, so the extension should no longer be necessary. Please try v1.15 of Focus and let me know if it works for you (https://heyfocus.com/download/)
