### ISSUE TITLE
FF Focus extensions (2.8.0, 2.7.0) malfunctions w/ FF 117.0.1

### ISSUE THREAD

**Issue by posiczko** [bradjasper/focus-extension#18]
New FF Focus extension (v2.8.0, v2.7.0) installed with default settings shows as enabled on the Manage Your Extensions (`about:addons`) page:

![CleanShot 2023-09-19 at 08 08 19@2x](https://github.com/bradjasper/focus-extension/assets/386464/0e36e05f-ff9e-4077-be46-20b93e6dd9c1)

However, clicking on Extensions in the FF toolbar shows Focus extensions as disabled/grayed out with `Can't read and change data on this site` message.

Firefox Focus extension: v2.8.0, v2.7.0
Firefox version: 117.0.1
MacOS: 13.5.2

**Comment by bradjasper** [comment]
Hey @posiczko sorry for the issue, to confirm are you using Focus v1 or v2?

With Focus v1, the correct extension is 2.7.0 and with v2 it's 2.8.0

Also, was this previously working for you? If you start a Focus session does the extension try to do anything in Firefox?

**Comment by bradjasper** [comment]
Also I noticed I actually get this message too, but the extension does still work as expected. I'll investigate and see if I can get it fixed anyway, please let me know if blocking doesn't work for you!
