### ISSUE TITLE
opera os x

### ISSUE THREAD

**Issue by luglio7** [bradjasper/focus-extension#3]
The extension trigger an error on Opera 49 (mac os) and does not work.

**Comment by bradjasper** [comment]
Hello, thanks for the report. There does currently seem to be an issue with Opera and I am investigating. This doesn't seem to happen with other WebExtension platforms (Firefox/Vilvaldi) but I hope to get this resolved soon.

**Comment by luglio7** [comment]
thank you

**Comment by bradjasper** [comment]
Just a heads up that native Opera support is coming soon! It already works with Opera Developer Edition.
