### ISSUE TITLE
Firefox Quantum problems

### ISSUE THREAD

**Issue by pgaspar** [bradjasper/focus-extension#4]
I'm having trouble using the extension on Firefox Quantum (v57.0). I followed the instructions [here](https://heyfocus.com/docs/help/browser-extensions/) and installed `focus-extension-firefix-2.1.0.xpi`.

- The extension doesn't seem to be blocking anything while in Focus mode.
- Right after installation, a trial window briefly shows up on screen but immediately disappears.

I'm using OSX 10.13 and I'm still trying the trial - I'm not a subscriber yet.
Let me know if you need more information. Thank you!

**Comment by bradjasper** [comment]
Hello, please try the latest beta (https://heyfocus.com/releases/Focus-latest-beta.zip) and let me know if you're still experiencing any issues. Thanks!

**Comment by pgaspar** [comment]
It works! Thanks 👍
