### ISSUE TITLE
Submit to Google Chrome Store

### ISSUE THREAD

**Issue by sobolevn** [bradjasper/focus-extension#9]
It is really useful to install extensions from Google Chrome Store.
Do you consider to submit this app there?

**Comment by bradjasper** [comment]
Hello,  the extension shouldn't be needed on Chrome, please let me know if you are hitting an issue with this, thanks!

**Comment by sobolevn** [comment]
@bradjasper there are other browsers that use Chrome store. Like Brave, etc.
So, having an official extension in google store is still a good thing.

**Comment by bradjasper** [comment]
thanks for letting me know @sobolevn, I've made a note to get this done!
